/**
 * Copyright © 2026 Olcaytp. All rights reserved.
 * This file is part of the Construction Management Application.
 * Licensed under the MIT License. See LICENSE file for details.
 */

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Determine storage based on environment
let storageAdapter: any = localStorage;

// For Capacitor (mobile) apps, use localStorage which is available
// Supabase will handle session persistence automatically
if (typeof window !== 'undefined' && window.location.protocol === 'capacitor://') {
  console.log('[SUPABASE] Running in Capacitor environment');
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: storageAdapter,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce', // Improved security for mobile
  }
});

// Safe runtime sanity log (no secrets)
try {
  const keyTag = SUPABASE_ANON_KEY?.startsWith('eyJ')
    ? 'anon-jwt'
    : SUPABASE_ANON_KEY?.startsWith('sb_publishable_')
    ? 'publishable'
    : SUPABASE_ANON_KEY?.startsWith('sb_temp_')
    ? 'temp'
    : 'unknown';
  console.log(`[SUPABASE CLIENT] url=${SUPABASE_URL} key=${keyTag} persistSession=true autoRefreshToken=true`);
} catch {}