// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Safe runtime sanity log (no secrets)
try {
  const keyTag = SUPABASE_ANON_KEY?.startsWith('eyJ')
    ? 'anon-jwt'
    : SUPABASE_ANON_KEY?.startsWith('sb_publishable_')
    ? 'publishable'
    : SUPABASE_ANON_KEY?.startsWith('sb_temp_')
    ? 'temp'
    : 'unknown';
  console.log(`[SUPABASE CLIENT] url=${SUPABASE_URL} key=${keyTag}`);
} catch {}